# Generated by Django 3.2 on 2021-07-17 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_scholarprofile_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_nickname',
            field=models.CharField(default='no nickname', max_length=150),
        ),
    ]
