# Generated by Django 3.2 on 2021-07-17 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profile_user_nickname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_nickname',
            new_name='nickname',
        ),
    ]
