# Generated by Django 3.2 on 2021-07-09 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('adventure_slp', models.TextField(max_length=99999)),
                ('arena_slp', models.TextField(max_length=99999)),
                ('quest_slp', models.TextField(max_length=99999)),
            ],
        ),
    ]
