# Generated by Django 3.2 on 2021-07-09 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('slp_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskentry',
            name='adventure_slp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='taskentry',
            name='arena_slp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='taskentry',
            name='quest_slp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='taskentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
