# Generated by Django 3.2 on 2021-07-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slp_logs', '0002_auto_20210709_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_nickname', models.CharField(max_length=150)),
                ('manager_percent', models.PositiveSmallIntegerField(default=0)),
                ('investor_percent', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='taskentry',
            name='adventure_slp',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='taskentry',
            name='arena_slp',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='taskentry',
            name='quest_slp',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
